### ISSUE TITLE
Unexpected element. Parser was expecting element 'http://soap.sforce.com/2006/04/metadata:_default' but found 'http://soap.sforce.com/2006/04/metadata:default'

### ISSUE THREAD

**Issue by mickle00** [certinia/object-model-tool#2]
Have you guys seen this issue before? I'm doing some additional debugging, but, keeping everything the same, I've added an Account.object from my org into the demo/src/objects file, and now I get this error when I run "ant run"

This is on Ubuntu 14.04

Buildfile: /home/mike/Salesforce/object-model-tool/objectmodelutil/build.xml

run:
[propertyfile] Updating property file: /home/mike/Salesforce/object-model-tool/objectmodelutil/config.properties
[objectmodelutil] Error:
[objectmodelutil] Error getting Metadata from Xml.
[objectmodelutil]   Unexpected element. Parser was expecting element 'http://soap.sforce.com/2006/04/metadata:_default' but found 'http://soap.sforce.com/2006/04/metadata:default' /home/mike/Salesforce/object-model-tool/objectmodelutil/demo/src/objects/Account.object
[objectmodelutil] 

BUILD FAILED
/home/mike/Salesforce/object-model-tool/objectmodelutil/build.xml:41: com.financialforce.objectmodelutil.model.exception.retrieve.RetrieveXmlException: com.financialforce.objectmodelutil.model.exception.SpecificException
    at com.financialforce.objectmodelutil.model.processor.retrieve.RetrieveProcessorLocal.GetSObjects(RetrieveProcessorLocal.java:128)
    at com.financialforce.objectmodelutil.controller.CommandLineController.retrieveCall(CommandLineController.java:166)
    at com.financialforce.objectmodelutil.controller.CommandLineController.run(CommandLineController.java:85)
    at com.financialforce.objectmodelutil.Ant.execute(Ant.java:74)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: com.financialforce.objectmodelutil.model.exception.SpecificException
    at com.financialforce.objectmodelutil.model.processor.retrieve.RetrieveProcessorLocal.GetSObjects(RetrieveProcessorLocal.java:118)
    ... 20 more

Total time: 0 seconds

**Comment by bslaterffdc-zz** [comment]
I've never seen this particular issue before, but the conversion from a salesforce custom object to its java representation is known to be buggy. 

A fix to account for this this could be added to:
https://github.com/financialforcedev/object-model-tool/blob/master/objectmodelutil/src/main/java/com/financialforce/objectmodelutil/model/processor/retrieve/RetrieveProcessorLocal.java#L110

And:
https://github.com/financialforcedev/object-model-tool/blob/master/objectmodelutil/src/main/java/com/financialforce/objectmodelutil/model/processor/retrieve/RetrieveProcessorRemote.java#L169

Something like:
objectAsString = objectAsString.replace("http://soap.sforce.com/2006/04/metadata:default", "http://soap.sforce.com/2006/04/metadata:_default");

I will look at this issue but I can't commit to any kind of timeframe for publishing the fix / testing it.

Thanks for letting us know about this.
