### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by prolayc** [certinia/object-model-tool#3]
I am using following versions-
1. Java - 1.8
2. Ant - 1.9.6
3. Maven - 3.3.9
## During the ant build, I am getting the following error

C:\GitHubRepo\object-model-tool\objectmodelutil [master]> ant -verbose
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
Trying the default build file: build.xml
Buildfile: C:\GitHubRepo\object-model-tool\objectmodelutil\build.xml
Detected Java version: 1.8 in: C:\Program Files\Java\jdk1.8.0_72\jre
Detected OS: Windows 10
parsing buildfile C:\GitHubRepo\object-model-tool\objectmodelutil\build.xml with URI = file:/C:/GitHubRepo/object-model-tool/objectmodelutil/build.xml
Project base dir set to: C:\GitHubRepo\object-model-tool\objectmodelutil
parsing buildfile jar:file:/C:/apache-ant-1.9.6-bin/apache-ant-1.9.6/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/apache-ant-1.9.6-bin/apache-ant-1.9.6/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
Build sequence for target(s) `build' is [build]
Complete build sequence is [build, run, ]

build:
parsing buildfile jar:file:/C:/apache-ant-1.9.6-bin/apache-ant-1.9.6/lib/maven-artifact-ant-2.0.4-dep.jar!/org/apache/maven/artifact/ant/antlib.xml with URI = jar:file:/C:/apache-ant-1.9.6-bin/apache-ant-1.9.6/lib/maven-artifact-ant-2.0.4-dep.jar!/org/apache/maven/artifact/ant/antlib.xml from a zip file
parsing buildfile jar:file:/C:/GitHubRepo/object-model-tool/objectmodelutil/lib/maven-ant-tasks-2.1.3.jar!/org/apache/maven/artifact/ant/antlib.xml with URI = jar:file:/C:/GitHubRepo/object-model-tool/objectmodelutil/lib/maven-ant-tasks-2.1.3.jar!/org/apache/maven/artifact/ant/antlib.xml from a zip file
parsing buildfile jar:file:/C:/apache-ant-1.9.6-bin/apache-ant-1.9.6/lib/maven-artifact-ant-2.0.4-dep.jar!/org/apache/maven/artifact/ant/antlib.xml with URI = jar:file:/C:/apache-ant-1.9.6-bin/apache-ant-1.9.6/lib/maven-artifact-ant-2.0.4-dep.jar!/org/apache/maven/artifact/ant/antlib.xml from a zip file

BUILD FAILED
C:\GitHubRepo\object-model-tool\objectmodelutil\build.xml:21: java.lang.NoSuchMethodError: org.apache.maven.artifact.ant.DependenciesTask.setPathType(Ljava/lang/String;)V
        at org.apache.maven.artifact.ant.Mvn.downloadAndConfigureMaven(Mvn.java:108)
        at org.apache.maven.artifact.ant.Mvn.execute(Mvn.java:84)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 0 seconds
## C:\GitHubRepo\object-model-tool\objectmodelutil [master]>

Please help me to resolve the issue.
Thanks in advance.

**Comment by prolayc** [comment]
I tried to change the Pom.xml and set the Sorce and Target version to 1.8, but did not work. I could not find the jdkLevel tag in the original Maven POM reference website also. Need some help to build and run this tool.

**Comment by afawcett** [comment]
@bradslaterffdc any thoughts on this one?
